---
- name: Downloads and installs all necessary git and apt files for a development environment for vm's
  hosts: all
  become: true

  tasks:
  - name: 
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: install git, vim, zsh, and gcc libraries
    apt:
      name: [git, vim, gcc-multilib]
      state: present

    # apt: name={{ item  }} state=installed
    # with_items:
    # - git
    # - vim
    # - gcc-multilib
    # - zsh
  
  - name: set .ssh/config
    copy:
      src: ~/.ssh/config
      dest: ~/.ssh/config
  
  - name: pull git files from computer_systems repo
    git:
      repo: https://github.com/lnestelroad/Computer_Systems.git 
      dest: /home/vagrant/Computer_Systems

  - name: exicutes driver script and stores in file
    command: ./run.sh 
    args:
      chdir: /home/vagrant/Computer_Systems/Data_Lab/datalab-handout 

  - name: fetches log file and stores in current directory
    fetch:
      src: /tmp/DriverLog.txt 
      dest: . 
