---
- name: Downloads and installs all necessary git and apt files for a development environment for vm's
  hosts: all
  become: true

  tasks:
  - name: 
    apt:
      update_cache: yes

  - name: install git, vim, zsh, and gcc libraries
    apt: name={{ item  }} state=installed
    with_items:
    - git
    - vim
    - gcc-multilib
    - zsh
  
  - name: set .ssh/config
    copy:
      src: ~/.ssh/config
      dest: ~/.ssh/config
  
  - name: pull git files from computer_systems repo
    git:
      repo: https://github.com/lnestelroad/Computer_Systems.git 
      dest: /home/vagrant/Computer_Systems

  - name: set up vim configuration
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

  - name: set the correct values in .vimrc
    copy: 
      src: ./vimrc.txt
      dest: ~/.vimrc
 
  - name: exicutes bits.c script
    shell: sh ~/ComputerSystems/Data_Lab/datalab-handout/run.sh 
